.pre-commit-config.yaml
astro.config.mjs
src/content/docs/en/kitchen-sink/index.mdx

The kitchen sink page gives us a space to test our components and ensure they display correctly. They also give a public space to document the component's usage.

feat: add kitchen sink page for components

---

astro.config.mjs
src/components/ListTable.astro
src/components/atlas/BuildListTable.tsx
src/content/docs/en/kitchen-sink/index.mdx

Per https://adjustcom.atlassian.net/browse/THC-810, this change adds support for a list-table feature that mimics the syntax of Sphinx and renders a Table V2 table from ATLAS.
This approach might not be the best one. I've tried to render the component list as HTML then iterate through the elements to create the headers and columns, but I'm sure there's a much easier way so I'd appreciate any pointers.

Add ATLAS tables

---

astro.config.mjs
package-lock.json
package.json
src/content/docs/en/kitchen-sink/typography.mdx

As pointed out by KK, we should probably rely on Figma for our diagrams:
1. It's part of our existing workflow
2. Images can be loaded much more efficiently than JS-powered Mermaid
3. It facilitates translations
For these reasons, this PR removes Mermaid and its dependencies from the build. In future, we should come up with a strategy for adding translated diagrams programatically.

Remove mermaid

---

.vale.ini
src/content/docs/en/api/device-api/authentication.mdx
src/content/docs/en/api/device-api/forget.mdx
src/content/docs/en/api/device-api/index.mdx
src/content/docs/en/api/device-api/inspect.mdx
src/content/docs/en/api/index.mdx
src/content/docs/en/api/partials/_Authentication.mdx
tsconfig.json

Initial import of the Device API documentation. Requires some components to be imported and updated.
https://adjustcom.atlassian.net/browse/ADAPP-16881

Import device API documentation

---

.vscode/markdown.code-snippets
astro.config.mjs
src/components/Abbr.astro
src/components/Tooltip.astro
src/components/atlas/BuildTooltip.tsx
src/content/docs/en/kitchen-sink/typography.mdx

Adds support for Atlas tooltips.

Add tooltip

---

src/content/docs/en/sdk/ios/configuration/deep-links/data-points.mdx
src/content/docs/en/sdk/ios/configuration/deep-links/deferred.mdx
src/content/docs/en/sdk/ios/configuration/deep-links/direct.mdx
src/content/docs/en/sdk/ios/configuration/deep-links/resolution.mdx
src/content/docs/en/sdk/ios/configuration/deep-links/testing.mdx
src/content/docs/en/sdk/ios/configuration/skad.mdx
src/content/docs/en/sdk/ios/features/ad-revenue.mdx
src/content/docs/en/sdk/ios/features/events.mdx
src/content/docs/en/sdk/ios/index.mdx
src/content/docs/en/sdk/unity/configuration/att.mdx
src/content/docs/en/sdk/unity/configuration/deep-links.mdx
src/content/docs/en/sdk/unity/configuration/skad.mdx
src/content/docs/en/sdk/unity/features/ad-revenue.mdx
src/content/docs/en/sdk/unity/features/callbacks.mdx
src/content/docs/en/sdk/unity/features/events.mdx
src/content/docs/en/sdk/unity/index.mdx
src/content/docs/en/sdk/web/features/events.mdx
src/content/docs/en/sdk/web/reference/adjust/recording.mdx
src/styles/index.css

As discussed with Marcie, we tend to rely on accordions to make pages look neater. However, it isn't obvious to all users that accordions are expandable, which can lead to important information being hidden.
Accordions should be used only to hide **supplementary** or **non-essential** information that is available elsewhere, such as lists of parameters. They should **not** be used to hide examples, alternative methods for achieving a goal, nor for anything else that is essential to informing the reader. This information should be structured appropriately in the page to make it more easily searchable and to give the reader all the information they might need in one glance. In cases of multiple sets of instructions being available, Tab elements are preferred.
This PR removes unnecessary …

Reduce accordion usage

---

.github/scripts/fix-i18n.sh
.github/workflows/fix_translations.yml

This PR adds a new script and GitHub action for fixing files received from Smartling. It anticipates a file structure like this: `src/content/docs/**/*-${locale}.mdx`.
The script fixes all MDX-related formatting issues as well as performing string replacements for the `en` locale code. It is written entirely in POSIX-compliant shell for maximum portability.

Add script for translation fixes

---

src/content/docs/api/rs-api/authentication.mdx

This PR aims to fix issues with breaks in Smartling jobs caused by inline MDX components.

Remove inline elements from RS API

---

src/content/docs/sdk/android/index.mdx
src/content/docs/sdk/flutter/index.mdx
src/content/docs/sdk/react-native/index.mdx
src/content/docs/sdk/unity/index.mdx

Related to https://adjustcom.atlassian.net/browse/ADAPP-17470

Add MIR referrer details for each SDK

---

src/content/docs/sdk/ios/features/att.mdx

Adds documentation for the double endpoint solution and its interaction with ATT.
https://adjustcom.atlassian.net/browse/ADAPP-17446

Double endpoint documentation

---

astro.config.mjs

As the site grows, each build takes longer to complete. Astro has an [experimental caching feature](https://docs.astro.build/en/reference/configuration-reference/#experimentalcontentcollectioncache) which aims to reduce this by creating manifests of the content collection for each build and building only what is changed in each version.
Previously, this caused issues with styling and output. However, with the stabilization of our content collection and the inlining of all critical styles it's worth enabling this again to see if it can improve build performance.

Reenable experimental build cache

---

.vscode/markdown.code-snippets
astro.config.mjs
package-lock.json
package.json
src/content/docs/sdk/android/index.mdx
src/declarations.d.ts
src/integrations/fetchSdkVersions.ts
src/integrations/remarkReplaceVersions.ts

This PR includes a process for automating the interpolation of SDK version numbers inside code blocks. Since we can't programatically overwrite these values using standard MDX interpolation, we need to rely on plugins.
> **Note**: This process runs only during **production builds** to avoid rate limits being hit on the GitHub API. Dummy values are returned by default.
The process follows these steps:
1. The server runs a process (`src/integrations/fetchSdkVersions.ts`) to do one of the following:
* If the server is running in **preview** mode, return a list of dummy versions
* If the server is running in **production** mode, fetch the latest version numbers for each platform from GitHub
3. These values are passed to a remark plugin (`src/integrations/remarkReplaceVersions.ts`), which …

THC-948-automate-sdk-version-numbers

---

src/components/Layout/Footer/FooterLanguageSwitch.astro
src/components/Layout/Header/MainHeader.astro
src/components/Layout/Header/MobileHeader.astro
src/components/Layout/LeftSidebar/Navigation.astro
src/components/Layout/LeftSidebar/SidebarSearch/SidebarSearch.astro
src/i18n/locales.ts
src/i18n/translations/en.json
src/i18n/translations/ja.json
src/i18n/translations/ko.json
src/i18n/translations/zh.json
src/i18n/ui.ts
src/i18n/utils.ts
src/layouts/MainLayout.astro
src/pages/[lang]/[...slug].astro
src/pages/[lang]/index.astro

Added basic setup for the UI translations using this approach: https://docs.astro.build/en/recipes/i18n/#translate-ui-strings
I`ve created a separate folder for the translations strings to be sure that we will be able to properly pickup these files on the Smartling side

THC 943 set up translatable UI strings

---

src/components/Version/ApiVersionSwitch.tsx
src/components/Version/SdkVersionSwitch.tsx
src/components/utils/queryParamHelpers.ts

Closes https://adjustcom.atlassian.net/browse/THC-1011
Enables controlling SDK versioned content with a query param in the URL (e.g. `?version={version}`) if the version specified is supported.

Enable sharing versioned content with query param

---

src/components/Layout/PageContent/PageContent.astro
src/components/Version/SdkVersionSwitch.tsx
src/content/config.ts
src/content/docs/api/campaign-api/get-links.mdx
src/content/docs/api/campaign-api/get-sublinks.mdx
src/content/docs/sdk/android/index.mdx
src/layouts/MainLayout.astro

The current approach to the version switcher uses a lot of expensive checks to see if versioned content is present. This update changes the approach to use the `multiVersion` property in a file's frontmatter to determine if the switcher should appear.

Use frontmatter for multiversion docs

---

astro.config.mjs
package-lock.json
package.json
src/components/Layout/PageContent/PageContent.astro
src/components/Layout/RightSidebar/TableOfContents/index.tsx
src/components/Version/ApiVersionComponent.tsx
src/components/Version/SdkVersionComponent.tsx
src/components/utils/queryParamHelpers.ts
src/utils/helpers/toc/getTocHeadings.ts

Currently, the Table of Contents is rendered upon page load and stays that way. However, with version switchers the headers present and visible on the page might change when the version is changed.
This PR registers a new event listener that checks for changes to the URL `version` param and updates the ToC with only visible headers that are available on the page.

Make ToC update with version change

---

.github/scripts/extract_links.py
.github/workflows/check_links.yml
src/content/docs/sdk/android/setup/preinstall-tool-ja.mdx
src/content/docs/sdk/android/setup/preinstall-tool-ko.mdx
src/content/docs/sdk/android/setup/preinstall-tool-zh.mdx
src/content/docs/sdk/ios/features/deep-links/resolution-ja.mdx
src/content/docs/sdk/ios/features/deep-links/resolution-ko.mdx
src/content/docs/sdk/ios/features/deep-links/resolution-zh.mdx
src/content/docs/sdk/smart-banner/deep-linking.mdx

Closes https://adjustcom.atlassian.net/browse/THC-1009
Since we use link syntax to set up persistent headers in files, our link checking step isn't working. To resolve this, this PR adds a script that pull out all Markdown links excluding those found in headers and passes their output to Lychee.

Add extraction step for links

---

src/utils/helpers/toc/getTocHeadings.ts

Currently, headers are updated on the page based on the version selected. This is due to a limitation in how multi-version documents are handled.
This change updates this logic to remove headers from any hidden blocks. This means all headers remain unique, and the header IDs will be added only when the the blocks are visible.
This is a workaround to improve behavior until our content collection issues are resolved.

Improve versioned header links

---

.env.example
astro.config.mjs
src/env.d.ts
src/integrations/fetchSdkVersions.ts

Currently, the GitHub token isn't being imported properly due to not having a `VITE_` prefix. This PR fixes this issue and adds a log to let people know if the token is loaded during build.

Fix token import

---

src/content/docs/sdk/ios/configuration.mdx

As per ticket ES-7945, removed asterisk from the isEnabledWithCompletionHandler method.

Removed asterisk from method

---

package.json

Fix was done by this approach: https://vercel.com/guides/troubleshooting-sigkill-out-of-memory-errors#4.-increase-memory-allocation-for-node

THC-1044 changed old space size to 7 GB

---

src/content/docs/sdk/flutter/features/events.mdx

I have tried to clean up the event section for Flutter SDK v5. Things to keep in mind:
- I have updated the syntax to match Flutter SDK v5.
- I don't know how to create v4/v5 toggles, so you guys need to do that.
- I have also went with removal of bigger example code snippets which to me personally looked like too cumbersome -> too many clutter code from Flutter app which is not that important for the logic itself. So what I did was just to use log output (which I think is nice to have!) and just added it below most basic code snippet which is showcasing the usage of the certain API.
In case you are not fancying these changes (that are not related to the SDK v5 API itself), feel free to alter them as you wish.

Update event section for Flutter SDK v5

---

src/components/pages/search/DevHubHits/DevHubSearchResultCard.tsx

Previously we changed hit directly to add ellipsis, but this adds some "blinking" effect when we switch pages for the search results(with search query). I`ve removed the previous logic and added an ellipsis through a pseudo-elements

Changed logic for the ellipsis

---

src/integrations/fetchSdkVersions.ts
src/integrations/remarkReplaceVersions.ts

Currently, the version fetch logic has an extra step to strip the leading "v" in the remark plugin. For Markdoc, this needs to be stripped before it's written to a file. To make this step work for both MDX and Markdoc, this PR:
With this setup, the following markup works for MDX:
````mdx
```js
var foo = "$ANDROID_V5_VERSION";
```
````
And the following for Mdoc:
````md
```js
var foo = "{% $versions.android.v5 %}";
```
````

Make version fetch markup-independent

---

public/404.html
src/middleware.ts

Currently, if you hit a nonexistent locale such as `fr` or `es`, you will get a 404. Instead, we should initially try to push users to the `en` root. If that doesn't exist, then a 404 can be shown.

Nonexistent locale redirect

---

src/content/docs/en/sdk/unity/v4/index.mdoc
src/content/docs/en/sdk/unity/v4/index.mdx
src/content/docs/en/sdk/unity/v5/index.mdoc

- Jira issue link: [ADAPP-18952](https://adjustcom.atlassian.net/browse/ADAPP-18952)
In the Unity integration app, under Build your app, there were tabs for iOS and Android. Both have internal headings with the same “names” and anchor links, creating a weird duplication/broken links in the internal ToC (the one on the right).
Extracted the iOS & Android instructions into standard sections in the document, and deleted the `tabs` component.
No text changed.
[ADAPP-18952]: https://adjustcom.atlassian.net/browse/ADAPP-18952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reformat iOS & Android instructions Tabs as standard sections

---

src/components/HeadSEO.astro
src/components/Layout/Footer/static.ts
src/pages/[lang]/index.astro
src/pages/[lang]/search.astro

- Jira issue link: https://adjustcom.atlassian.net/browse/THC-1084
- Fixed double slash for the Adjust links in the Footer
- Fixed error when "undefined" is shown instead of the page title for the Main and Search pages

THC 1084 double slash in footer links

---

src/content/docs/en/sdk/flutter/v5/features/deep-links.mdx
src/content/docs/en/sdk/ios/v5/index.mdoc
src/content/docs/ja/sdk/flutter/v5/features/deep-links.mdx
src/content/docs/ja/sdk/ios/v5/index.mdoc
src/content/docs/ko/sdk/flutter/v5/features/deep-links.mdx
src/content/docs/ko/sdk/ios/v5/index.mdoc
src/content/docs/zh/sdk/flutter/v5/features/deep-links.mdx
src/content/docs/zh/sdk/ios/v5/index.mdoc

- https://adjust.slack.com/archives/C0284S09H/p1738744284786859?thread_ts=1738136134.344279&cid=C0284S09H
- https://adjust.slack.com/archives/G1VTG519S/p1738147318505719?thread_ts=1737025804.101109&cid=G1VTG519S
Fixes iOS header under Flutter and Webbridge guide
| Android              | :x:  | :x:  | :x:  |
| Unity                  | :x:  | :x:  | :x:  |
| React Native     | :x:  | :x:  | :x:  |
| Flutter                | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Cordova             | :x:  | :x:  | …

Update ios header under flutter guide

---

src/content/docs/ja/api/s2s-api/sessions.mdx
src/content/docs/ko/api/s2s-api/sessions.mdx
src/content/docs/zh/api/s2s-api/sessions.mdx

- Jira issue link: https://adjustcom.atlassian.net/browse/FECORE-628
Fix for the localized versions of https://dev.adjust.com/en/api/s2s-api/sessions doc, to hide anchor links after headers

[FECORE-628] s2s-api/sessions fixed headers links for the localized docs

---

src/content/docs/en/sdk/ios/v5/features/att.mdx

- Jira issue link: https://adjustcom.atlassian.net/browse/SDK-2211
Added ability to disable SDK's interaction with AppTrackingTransparency.framework API.
| Platform                | ZH                 | JA                 | KO                 | EN
| ----------------------- | ------------------ | ------------------ | ------------------ | -----------------|
| iOS                     | :x: | :x: | :x: |✅

Added ability to disable AppTrackingTransparency.framework uage
