adjust/dev-docs

src/components/Callout.astro, src/components/atlas/BuildAccordion.tsx, src/components/atlas/BuildBanner.tsx, src/declarations.d.ts
=> TSX components

astro.config.mjs, package-lock.json, package.json, src/components/Function.astro, src/components/GitHubRender.astro, src/content/docs/en/kitchen-sink/index.mdx, src/content/docs/en/web/reference/config-2.mdx, src/content/docs/en/web/reference/config-3.mdx, src/content/docs/en/web/reference/config.mdx, src/content/docs/en/web/reference/ios/config-1.mdx, src/content/docs/ja/web/reference/config-2.mdx, src/content/docs/ja/web/reference/config-3.mdx, src/content/docs/ja/web/reference/config.mdx, src/content/docs/ja/web/reference/ios/config-1.mdx
Adds support for function documentation with GitHub permalink support.
=> Add support for functions

src/components/GitHubRender.astro, src/components/utils/fetchGithubContent.ts, src/components/utils/getInfoFromUrl.ts, src/components/utils/getLines.ts, src/declarations.d.ts
Refactors the GitHub link render component to use separate helper functions for maintainability.
=> Refactor GitHub link render into utils

.vale.ini, astro.config.mjs, src/components/GuiLabel.astro, src/components/MenuSelection.astro
Adds GuiLabel and MenuSelection interfaces with associated vale ignore rules
=> Inline text components

src/content/docs/en/api/gdpr-api/index.mdx
https://adjustcom.atlassian.net/browse/ADAPP-16882
=> Add GDPR API documentation

src/content/docs/en/api/ad-spend-api/cost-endpoint.mdx, src/content/docs/en/api/ad-spend-api/cost-id.mdx, src/content/docs/en/api/ad-spend-api/index.mdx, src/content/docs/en/api/device-api/index.mdx
https://adjustcom.atlassian.net/browse/ADAPP-16877
=> Add ad spend API docs

src/content/docs/en/api/blocklist-api/authentication.mdx, src/content/docs/en/api/blocklist-api/blocklist.mdx, src/content/docs/en/api/blocklist-api/index.mdx, src/content/docs/en/api/blocklist-api/unblocklist.mdx, src/content/docs/en/api/partials/_Blocklist.mdx
https://adjustcom.atlassian.net/browse/ADAPP-16878
=> Add blocklist API

src/components/atlas/BuildAccordion.tsx, src/components/utils/htmlWithTitles.tsx, src/content/docs/en/api/app-automation-api/app-endpoint.mdx, src/content/docs/en/api/app-automation-api/authentication.mdx, src/content/docs/en/api/app-automation-api/campaign-endpoint.mdx, src/content/docs/en/api/app-automation-api/channel-setup.mdx, src/content/docs/en/api/app-automation-api/index.mdx, src/content/docs/en/api/app-automation-api/status-endpoint.mdx, src/content/docs/en/api/blocklist-api/authentication.mdx, src/content/docs/en/api/device-api/authentication.mdx
https://adjustcom.atlassian.net/browse/ADAPP-16880
=> Import app automation API docs

src/content/docs/en/api/partials/_KS-params.mdx
https://adjustcom.atlassian.net/browse/ADAPP-17258
=> Add missing os names to KPI service

src/content/docs/en/api/kpi-service/cohort-metrics.mdx, src/content/docs/en/sdk/android/configuration/deep-linking.mdx, src/content/docs/en/sdk/flutter/configuration/privacy.mdx, src/content/docs/en/sdk/ios/configuration/external-device-id.mdx, src/content/docs/en/sdk/ios/index.mdx
* [404] [https://dev-docs-dss2oqwwi-product-content.vercel.app/api/kpi-service/grouping.md](https://dev-docs-dss2oqwwi-product-content.vercel.app/api/kpi-service/grouping.md) | Failed: Network error: Not Found
* [404] [https://dev-docs-dss2oqwwi-product-content.vercel.app/en/sdk/android/configuration/deep-links](https://dev-docs-dss2oqwwi-product-content.vercel.app/en/sdk/android/configuration/deep-links) | Cached: Error (cached)
* [404] [https://dev-docs-dss2oqwwi-product-content.vercel.app/en/sdk/flutter/reference/adjthirdpartysharing](https://dev-docs-dss2oqwwi-product-content.vercel.app/en/sdk/flutter/reference/adjthirdpartysharing) | Failed: Network error: Not Found
* [404] [https://dev-docs-dss2oqwwi-product-content.vercel.app/ios/recording/session-parameters.md](https://dev-docs-dss …
=> Fix broken links from report

src/content/docs/en/sdk/android/features/ad-revenue.mdx, src/content/docs/en/sdk/android/integrations/adx.mdx, src/content/docs/en/sdk/ios/features/ad-revenue.mdx, src/content/docs/en/sdk/ios/integrations/adx.mdx, src/content/docs/en/sdk/unity/features/ad-revenue.mdx, src/content/docs/en/sdk/unity/integrations/adx.mdx
Starting off with Unity since that's the example we've received. This is the basic format for the revenue integration I think we should use. @KaihkashanAdjust could you take a look and let me know what you think?
=> Add AD(X) docs

src/content/docs/en/sdk/android/features/events.mdx, src/content/docs/en/sdk/flutter/features/events.mdx, src/content/docs/en/sdk/ios/features/events.mdx, src/content/docs/en/sdk/react-native/features/events.mdx, src/content/docs/en/sdk/unity/features/events.mdx
Relates to ADAPP-17361. Adds log examples for event logging.
=> Add event logging information

src/content/docs/api/campaign-api/create-tracker.mdx, src/content/docs/api/campaign-api/get-partners.mdx, src/content/docs/api/campaign-api/get-subtrackers.mdx, src/content/docs/api/campaign-api/get-trackers.mdx, src/content/docs/sdk/android/features/deep-linking.mdx
Relates to https://adjustcom.atlassian.net/browse/ADAPP-17482
=> Campaign api pagination change

src/content/docs/sdk/android/integrations/admob.mdx, src/content/docs/sdk/ios/integrations/admob.mdx, src/content/docs/sdk/unity/integrations/admob.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-17749
=> Admob ILAR instructions

src/content/docs/sdk/ios/index-ja.mdx, src/content/docs/sdk/ios/index-ko.mdx, src/content/docs/sdk/ios/index-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:finuqmifnits
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/4e8f0650d8b9ae3627ebbd1822e9fe2137b33e09
=> Smartling translations are updated for commit 4e8f0650d8b9ae3627ebbd1822e9fe2137b33e09 from main

.github/workflows/fix_translations.yml
Adds a job to lint any localized files
=> Lint localized files

src/content/docs/sdk/android/plugins/samsung-referrer-plugin-ja.mdx, src/content/docs/sdk/android/plugins/samsung-referrer-plugin-ko.mdx, src/content/docs/sdk/android/plugins/samsung-referrer-plugin-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:briayx59bnhe
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/fc3a0fece15f7c91e88875614432a9553b3491c5
=> Smartling translations are updated for commit fc3a0fece15f7c91e88875614432a9553b3491c5 from main

src/content/docs/api/s2s-api/security-ja.mdx, src/content/docs/api/s2s-api/security-ko.mdx, src/content/docs/api/s2s-api/security-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:wvlquuwwndbe
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/351ed9f0318ecd964cf41c6f7027b256690b3854
=> Smartling translations are updated for commit 351ed9f0318ecd964cf41c6f7027b256690b3854 from main

src/content/docs/sdk/android/plugins/samsung-clouddev-ja.mdx, src/content/docs/sdk/android/plugins/samsung-clouddev-ko.mdx, src/content/docs/sdk/android/plugins/samsung-clouddev-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:vpoyxpnhcv7y
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/ba17945f4728f951f7b540a6954757beec2cb529
=> Smartling translations are completed for commit ba17945f4728f951f7b540a6954757beec2cb529 from main

src/content/docs/sdk/ios/index-ja.mdx, src/content/docs/sdk/ios/index-ko.mdx, src/content/docs/sdk/ios/index-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:dr1nfrqjsscw
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/e4bb838f1cf76357160a2b2efaf918198a473381
=> Smartling translations are completed for commit e4bb838f1cf76357160a2b2efaf918198a473381 from main

src/content/docs/sdk/android/plugins/xiaomi-referrer-plugin-ja.mdx, src/content/docs/sdk/android/plugins/xiaomi-referrer-plugin-ko.mdx, src/content/docs/sdk/android/plugins/xiaomi-referrer-plugin-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:krojdtlz8ykg
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/a8075165b8fcf967beea7ec477896d21f91e8acb
=> Smartling translations are updated for commit a8075165b8fcf967beea7ec477896d21f91e8acb from main

src/content/docs/sdk/android/features/events-ja.mdx, src/content/docs/sdk/android/features/events-ko.mdx, src/content/docs/sdk/android/features/events-zh.mdx, src/content/docs/sdk/flutter/features/events-ja.mdx, src/content/docs/sdk/flutter/features/events-ko.mdx, src/content/docs/sdk/flutter/features/events-zh.mdx, src/content/docs/sdk/ios/features/events-ja.mdx, src/content/docs/sdk/ios/features/events-ko.mdx, src/content/docs/sdk/ios/features/events-zh.mdx, src/content/docs/sdk/react-native/features/events-ja.mdx, src/content/docs/sdk/react-native/features/events-ko.mdx, src/content/docs/sdk/react-native/features/events-zh.mdx, src/content/docs/sdk/unity/features/events-ja.mdx, src/content/docs/sdk/unity/features/events-ko.mdx, src/content/docs/sdk/unity/features/events-zh.mdx, src/content/docs/sdk/web/features/events-ja.mdx, src/content/docs/sdk/web/features/events-ko.mdx, src/content/docs/sdk/web/features/events-zh.mdx, src/content/docs/sdk/windows/features/events-ja.mdx, src/content/docs/sdk/windows/features/events-ko.mdx, src/content/docs/sdk/windows/features/events-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:n23pgftd5bwf
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/388cfcc447f57a8c916129629abce1d5742b0b3f
=> Smartling translations are completed for commit 388cfcc447f57a8c916129629abce1d5742b0b3f from main

src/components/pages/search/PlatformBadges/PlatformBadges.tsx
Closes https://adjustcom.atlassian.net/browse/THC-984
=> Add Android and update iOS label

src/content/docs/sdk/android/configuration-ja.mdx, src/content/docs/sdk/android/configuration-ko.mdx, src/content/docs/sdk/android/configuration-zh.mdx, src/content/docs/sdk/flutter/configuration-ja.mdx, src/content/docs/sdk/flutter/configuration-ko.mdx, src/content/docs/sdk/flutter/configuration-zh.mdx, src/content/docs/sdk/ios/configuration-ja.mdx, src/content/docs/sdk/ios/configuration-ko.mdx, src/content/docs/sdk/ios/configuration-zh.mdx, src/content/docs/sdk/react-native/configuration-ja.mdx, src/content/docs/sdk/react-native/configuration-ko.mdx, src/content/docs/sdk/react-native/configuration-zh.mdx, src/content/docs/sdk/unity/configuration-ja.mdx, src/content/docs/sdk/unity/configuration-ko.mdx, src/content/docs/sdk/unity/configuration-zh.mdx, src/content/docs/sdk/windows/configuration-ja.mdx, src/content/docs/sdk/windows/configuration-ko.mdx, src/content/docs/sdk/windows/configuration-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:edqbjfri03iu
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/1f9fa90a77e2029b753b51d91e6665fa6aefa1a5
=> Smartling translations are completed for commit 1f9fa90a77e2029b753b51d91e6665fa6aefa1a5 from main

src/content/docs/sdk/android/features/privacy-ja.mdx, src/content/docs/sdk/android/features/privacy-ko.mdx, src/content/docs/sdk/android/features/privacy-zh.mdx, src/content/docs/sdk/flutter/features/privacy-ja.mdx, src/content/docs/sdk/flutter/features/privacy-ko.mdx, src/content/docs/sdk/flutter/features/privacy-zh.mdx, src/content/docs/sdk/ios/features/deep-links/data-points-ja.mdx, src/content/docs/sdk/ios/features/deep-links/data-points-ko.mdx, src/content/docs/sdk/ios/features/deep-links/data-points-zh.mdx, src/content/docs/sdk/ios/features/privacy-ja.mdx, src/content/docs/sdk/ios/features/privacy-ko.mdx, src/content/docs/sdk/ios/features/privacy-zh.mdx, src/content/docs/sdk/react-native/features/privacy-ja.mdx, src/content/docs/sdk/react-native/features/privacy-ko.mdx, src/content/docs/sdk/react-native/features/privacy-zh.mdx, src/content/docs/sdk/unity/features/privacy-ja.mdx, src/content/docs/sdk/unity/features/privacy-ko.mdx, src/content/docs/sdk/unity/features/privacy-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:chum4ahoxsvc
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/2cb3ca03214eeee93f34f4b221dd9b0e770d6a06
=> Smartling translations are completed for commit 2cb3ca03214eeee93f34f4b221dd9b0e770d6a06 from main

src/content/docs/sdk/ios/features/att-ja.mdx, src/content/docs/sdk/ios/features/att-ko.mdx, src/content/docs/sdk/ios/features/att-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:9jakbjlwjlj4
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/8df5b7dda56642dad0972820236da20b20c58b1d
=> Smartling translations are completed for commit 8df5b7dda56642dad0972820236da20b20c58b1d from main

src/content/docs/sdk/ios/configuration-ja.mdx, src/content/docs/sdk/ios/configuration-ko.mdx, src/content/docs/sdk/ios/configuration-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:6yzvoovetunc
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/a7d1c07c65333279de7531d299b98515e6b2da9d
=> Smartling translations are completed for commit a7d1c07c65333279de7531d299b98515e6b2da9d from main

src/content/docs/sdk/unity/index-ja.mdx, src/content/docs/sdk/unity/index-ko.mdx, src/content/docs/sdk/unity/index-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:p9uyjluudgym
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/da1b51cb67c692237a2c6c67ab4e0135b7ff6832
=> Smartling translations are completed for commit da1b51cb67c692237a2c6c67ab4e0135b7ff6832 from main

src/content/docs/sdk/flutter/features/att.mdx, src/content/docs/sdk/ios/features/att.mdx, src/content/docs/sdk/react-native/features/att.mdx, src/content/docs/sdk/unity/features/att.mdx
Closes https://adjustcom.atlassian.net/browse/ES-7241
=> Add custom prompt timing docs

src/content/docs/api/ad-spend-api/cost-endpoint-ja.mdx
Please review this manually triggered translation push from the configuration set 'GitHub connector' in your Smartling project https://dashboard.smartling.com/app/projects/224fc9b33/github-connector/configurationSets/2d8067270a23
=> Smartling on-demand translation delivery from main

src/components/Layout/PageContent/PageContent.astro, src/content/docs/api/campaign-api/index.mdx, src/content/docs/api/device-api/index.mdx
Closes https://adjustcom.atlassian.net/browse/THC-992
=> Fix article formatting

src/components/Layout/AudienceDropdown/index.tsx
Closes https://adjustcom.atlassian.net/browse/THC-981
=> Center platform text

src/components/Layout/PageContent/PageContent.astro
Closes https://adjustcom.atlassian.net/browse/THC-988
=> Ensure link text matches size of Banner

src/i18n/translations/en.json
Closes https://adjustcom.atlassian.net/browse/THC-983
=> Update search placeholder

src/content/docs/api/ad-spend-api/cost-endpoint-ja.mdx, src/content/docs/api/ad-spend-api/cost-endpoint-ko.mdx, src/content/docs/api/ad-spend-api/cost-endpoint-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:is5pnj0peuek
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/cf7235e756f8d02a577e3ee03014792f67269bc8
=> Smartling translations are updated for commit cf7235e756f8d02a577e3ee03014792f67269bc8 from main

src/components/Layout/Header/MainHeader.astro
Closes https://adjustcom.atlassian.net/browse/THC-980
=> Add hover decoration to dashboard link

src/components/Layout/PageContent/PageContent.astro
Closes https://adjustcom.atlassian.net/browse/THC-989
=> Fix vertical alignment of text in tables

src/content/docs/api/campaign-api/index-ja.mdx, src/content/docs/api/campaign-api/index-ko.mdx, src/content/docs/api/campaign-api/index-zh.mdx, src/content/docs/api/device-api/index-ja.mdx, src/content/docs/api/device-api/index-ko.mdx, src/content/docs/api/device-api/index-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:sowftbuofcpe
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/752609d83d82f70f97a2b697263777f5505282b0
=> Smartling translations are updated for commit 752609d83d82f70f97a2b697263777f5505282b0 from main

src/i18n/translations/ja.json, src/i18n/translations/ko.json, src/i18n/translations/zh.json
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:u12cqfq3sqww
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/5fde69c00e5495caa1c524743f0a2b789e8f17be
=> Smartling translations are completed for commit 5fde69c00e5495caa1c524743f0a2b789e8f17be from main

src/components/Layout/Footer/FooterContent.astro, src/components/Layout/Footer/FooterMain.astro, src/components/Layout/Footer/static.ts
Fixes https://adjustcom.atlassian.net/browse/THC-1004
=> Use locale for footer links

src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx, src/content/docs/sdk/ios/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/ios/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/ios/migration/v4-to-v5-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:9bxdottayj0d
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/b424577374a2c5b90f8c225179a297595156fc25
=> Smartling translations are updated for commit b424577374a2c5b90f8c225179a297595156fc25 from main

src/content/docs/api/rs-api/csv.mdx, src/content/docs/api/rs-api/events.mdx, src/content/docs/api/rs-api/pivot.mdx, src/content/docs/api/rs-api/reports.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18040
=> Update automate URLs

src/components/Icons/react/ChevronLeft.tsx, src/components/Icons/react/ChevronRight.tsx, src/components/Layout/RightSidebar/TableOfContents/CollapsedTOC.tsx, src/components/Layout/RightSidebar/TableOfContents/index.tsx
Closes https://adjustcom.atlassian.net/browse/THC-1002
=> Make sidebar icon hover background fit container

src/content/docs/sdk/android/features/events.mdx, src/content/docs/sdk/android/index.mdx, src/content/docs/sdk/android/plugins/criteo.mdx, src/content/docs/sdk/android/plugins/imei-plugin.mdx, src/content/docs/sdk/android/plugins/oaid-plugin.mdx, src/content/docs/sdk/android/plugins/samsung-referrer-plugin.mdx, src/content/docs/sdk/android/plugins/sociomatic.mdx, src/content/docs/sdk/android/plugins/trademob.mdx, src/content/docs/sdk/android/plugins/vivo-referrer-plugin.mdx, src/content/docs/sdk/android/plugins/xiaomi-referrer-plugin.mdx, src/content/docs/sdk/ios/features/deep-links/testing.mdx, src/content/docs/sdk/ios/features/events.mdx, src/content/docs/sdk/ios/index.mdx, src/declarations.d.ts, src/integrations/fetchSdkVersions.ts, src/integrations/remarkReplaceVersions.ts
Closes https://adjustcom.atlassian.net/browse/THC-1013
=> Match SDK v4 and v5 in version overwrite

src/content/docs/api/campaign-api/get-links-ja.mdx, src/content/docs/api/campaign-api/get-links-ko.mdx, src/content/docs/api/campaign-api/get-links-zh.mdx, src/content/docs/api/campaign-api/get-sublinks-ja.mdx, src/content/docs/api/campaign-api/get-sublinks-ko.mdx, src/content/docs/api/campaign-api/get-sublinks-zh.mdx, src/content/docs/sdk/android/features/events-ja.mdx, src/content/docs/sdk/android/features/events-ko.mdx, src/content/docs/sdk/android/features/events-zh.mdx, src/content/docs/sdk/android/index-ja.mdx, src/content/docs/sdk/android/index-ko.mdx, src/content/docs/sdk/android/index-zh.mdx, src/content/docs/sdk/android/plugins/sociomatic-ja.mdx, src/content/docs/sdk/android/plugins/sociomatic-ko.mdx, src/content/docs/sdk/android/plugins/sociomatic-zh.mdx, src/content/docs/sdk/ios/features/events-ja.mdx, src/content/docs/sdk/ios/features/events-ko.mdx, src/content/docs/sdk/ios/features/events-zh.mdx, src/content/docs/sdk/ios/index-ja.mdx, src/content/docs/sdk/ios/index-ko.mdx, src/content/docs/sdk/ios/index-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:8tag5h8pknrl
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/ad71fb2af3a511b2f8ca4bfed9a9e09eeb960ca4
=> Smartling translations are updated for commit ad71fb2af3a511b2f8ca4bfed9a9e09eeb960ca4 from main

src/components/Accordion.astro, src/components/ApiVersion.astro, src/components/Callout.astro, src/components/Cards/CategoryCard.astro, src/components/Cards/TopCategoryCard.astro, src/components/CodeBlock.astro, src/components/FigmaEmbed/Caption.astro, src/components/FigmaEmbed/FigmaEmbed.astro, src/components/Layout/LeftSidebar/Navigation.astro, src/components/Layout/LeftSidebar/NavigationItem.tsx, src/components/Layout/LeftSidebar/SidebarHeader/SidebarHeader.astro, src/components/Layout/PageBreadcrumbs/PageBreadcrumbs.astro, src/components/MinorVersion.astro, src/components/SdkVersion.astro, src/components/Tab.astro, src/components/Table.astro, src/components/Tile.astro, src/components/atlas/BuildTable.tsx, src/components/utils/convertCase.ts, src/components/utils/extractCode.ts, src/components/utils/extractTabProps.ts, src/components/utils/queryParamHelpers.ts, src/integrations/remarkHeaderLinkToId.ts
This is a general cleanup of some component code for increased efficiency
=> Refactor components

.github/scripts/fix-i18n.sh, .vscode/markdown.code-snippets, astro.config.mjs, src/components/ListColumns.astro, src/components/index.ts, src/content/docs/sdk/android/features/privacy.mdx, src/content/docs/sdk/cocos2dx/features/privacy.mdx, src/content/docs/sdk/flutter/features/privacy.mdx, src/content/docs/sdk/ios/features/privacy.mdx, src/content/docs/sdk/react-native/features/privacy.mdx, src/content/docs/sdk/unity/features/privacy.mdx
Updates the third party sharing methods for each SDK.
=> Add more examples for third party sharing

src/content/docs/sdk/ios/features/skad.mdx
Added 'none' coarse CV. See https://adjustcom.atlassian.net/browse/ADAPP-18029
=> Skad update 18029

src/content/docs/sdk/unity/migration/index.mdx, src/content/docs/sdk/unity/migration/v4-to-v5.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18127
=> Add Unity migration guide

.github/scripts/fix_i18n.py, src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx, src/content/docs/sdk/android/plugins/meta-install-referrer-ja.mdx, src/content/docs/sdk/android/plugins/meta-install-referrer-ko.mdx, src/content/docs/sdk/android/plugins/meta-install-referrer-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:zycktfv22cli
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/76c972f9b65e9be47af1a413ce6d441ce92817af
=> Smartling translations are completed for commit 76c972f9b65e9be47af1a413ce6d441ce92817af from main

src/content/docs/sdk/android/index-ja.mdx, src/content/docs/sdk/android/index-ko.mdx, src/content/docs/sdk/android/index-zh.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:njufgbnsbesd
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/1561e47a666b9b7a30633ec7c95bc0f08f60d7c0
=> Smartling translations are updated for commit 1561e47a666b9b7a30633ec7c95bc0f08f60d7c0 from main

src/content/docs/sdk/android/features/deep-linking-ja.mdx, src/content/docs/sdk/android/features/deep-linking-ko.mdx, src/content/docs/sdk/android/features/deep-linking-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:isitwry71khq
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/e28c45e8e43257ec23be4abfd36336f5f07ebd9b
=> Smartling translations are updated for commit e28c45e8e43257ec23be4abfd36336f5f07ebd9b from main

src/content/docs/sdk/cocos2dx/index-ja.mdx, src/content/docs/sdk/cocos2dx/index-ko.mdx, src/content/docs/sdk/cocos2dx/index-zh.mdx, src/content/docs/sdk/flutter/index-ja.mdx, src/content/docs/sdk/flutter/index-ko.mdx, src/content/docs/sdk/flutter/index-zh.mdx, src/content/docs/sdk/react-native/index-ja.mdx, src/content/docs/sdk/react-native/index-ko.mdx, src/content/docs/sdk/react-native/index-zh.mdx, src/content/docs/sdk/unity/index-ja.mdx, src/content/docs/sdk/unity/index-ko.mdx, src/content/docs/sdk/unity/index-zh.mdx, src/content/docs/sdk/web/index-ja.mdx, src/content/docs/sdk/web/index-ko.mdx, src/content/docs/sdk/web/index-zh.mdx, src/content/docs/sdk/windows/index-ja.mdx, src/content/docs/sdk/windows/index-ko.mdx, src/content/docs/sdk/windows/index-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:fvqyb95oa2w8
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/e4621cf48bd2a3e581758e79acc0ca0b05c05185
=> Smartling translations are completed for commit e4621cf48bd2a3e581758e79acc0ca0b05c05185 from main

src/content/docs/sdk/ios/features/skad-ja.mdx, src/content/docs/sdk/ios/features/skad-ko.mdx, src/content/docs/sdk/ios/features/skad-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:oqh5ojbghnei
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/f7d590fc558b7c8257a9795b6e8ce9715b6bba87
=> Smartling translations are completed for commit f7d590fc558b7c8257a9795b6e8ce9715b6bba87 from main

src/content/docs/sdk/smart-banner/deep-linking-ja.mdx, src/content/docs/sdk/smart-banner/deep-linking-ko.mdx, src/content/docs/sdk/smart-banner/deep-linking-zh.mdx, src/content/docs/sdk/smart-banner/index-ja.mdx, src/content/docs/sdk/smart-banner/index-ko.mdx, src/content/docs/sdk/smart-banner/index-zh.mdx, src/content/docs/sdk/smart-banner/init-options-ja.mdx, src/content/docs/sdk/smart-banner/init-options-ko.mdx, src/content/docs/sdk/smart-banner/init-options-zh.mdx, src/content/docs/sdk/smart-banner/integrations/adobe-launch-ja.mdx, src/content/docs/sdk/smart-banner/integrations/adobe-launch-ko.mdx, src/content/docs/sdk/smart-banner/integrations/adobe-launch-zh.mdx, src/content/docs/sdk/smart-banner/integrations/google-tag-manager-ja.mdx, src/content/docs/sdk/smart-banner/integrations/google-tag-manager-ko.mdx, src/content/docs/sdk/smart-banner/integrations/google-tag-manager-zh.mdx, src/content/docs/sdk/smart-banner/integrations/index-ja.mdx, src/content/docs/sdk/smart-banner/integrations/index-ko.mdx, src/content/docs/sdk/smart-banner/integrations/index-zh.mdx, src/content/docs/sdk/smart-banner/integrations/shopify-ja.mdx, src/content/docs/sdk/smart-banner/integrations/shopify-ko.mdx, src/content/docs/sdk/smart-banner/integrations/shopify-zh.mdx, src/content/docs/sdk/smart-banner/show-hide-ja.mdx, src/content/docs/sdk/smart-banner/show-hide-ko.mdx, src/content/docs/sdk/smart-banner/show-hide-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:xx4xjwxc9qee
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/a633f7c815c08ec1180cc40f8e37f3f3535bc553
=> Smartling translations are completed for commit a633f7c815c08ec1180cc40f8e37f3f3535bc553 from main

src/content/docs/sdk/react-native/features/deep-links-ja.mdx, src/content/docs/sdk/react-native/features/deep-links-ko.mdx, src/content/docs/sdk/react-native/features/deep-links-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:3ueorh8zgqkf
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/ccda75bff87b9b65b152c6b5a93ddb3ff92f3be7
=> Smartling translations are completed for commit ccda75bff87b9b65b152c6b5a93ddb3ff92f3be7 from main

src/content/docs/sdk/android/features/deep-linking-ja.mdx, src/content/docs/sdk/android/features/deep-linking-ko.mdx, src/content/docs/sdk/android/features/deep-linking-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:vjvxdv2gdc5p
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/7e8ee125e93803711148f45c3e3113e8755097f9
=> Smartling translations are updated for commit 7e8ee125e93803711148f45c3e3113e8755097f9 from main

src/content/docs/sdk/ios/features/skad-ja.mdx, src/content/docs/sdk/ios/features/skad-ko.mdx, src/content/docs/sdk/ios/features/skad-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:foshudqzb2sf
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/11c42d3f1042a113819c7cdb42e8f6035d57a0e0
=> Smartling translations are completed for commit 11c42d3f1042a113819c7cdb42e8f6035d57a0e0 from main

src/content/docs/sdk/unity/migration/index-ja.mdx, src/content/docs/sdk/unity/migration/index-ko.mdx, src/content/docs/sdk/unity/migration/index-zh.mdx, src/content/docs/sdk/unity/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/unity/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/unity/migration/v4-to-v5-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:0mjvdfcct8hi
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/423fe432a3b205160a76dcbb1af687e78438ca81
=> Smartling translations are completed for commit 423fe432a3b205160a76dcbb1af687e78438ca81 from main

src/content/docs/sdk/android/features/uninstall-reinstall-ja.mdx, src/content/docs/sdk/android/features/uninstall-reinstall-ko.mdx, src/content/docs/sdk/android/features/uninstall-reinstall-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:hldsvutdgftu
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/a541a758253843b1babf1e5847a0afae5f6eda87
=> Smartling translations are completed for commit a541a758253843b1babf1e5847a0afae5f6eda87 from main

src/content/docs/sdk/android/plugins/samsung-referrer-plugin-ja.mdx, src/content/docs/sdk/android/plugins/samsung-referrer-plugin-ko.mdx, src/content/docs/sdk/android/plugins/samsung-referrer-plugin-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:vrcm61czjaah
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/ba79191d2f62cda7e2883478986128e45b85d941
=> Smartling translations are updated for commit ba79191d2f62cda7e2883478986128e45b85d941 from main

src/content/docs/sdk/ios/features/callbacks-ja.mdx, src/content/docs/sdk/ios/features/callbacks-ko.mdx, src/content/docs/sdk/ios/features/callbacks-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:sayo6yl1hc7j
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/6fc9c87ef376bf2fc2c752c045248b1644883bfd
=> Smartling translations are completed for commit 6fc9c87ef376bf2fc2c752c045248b1644883bfd from main

src/components/AudienceDropdown.astro, src/components/Layout/Header/MainHeader.astro
Requested in the scope of this ticket: https://adjustcom.atlassian.net/browse/THC-1020?focusedCommentId=289231
=> THC-1020 added langs for the HC links

src/content/docs/sdk/react-native/features/deep-links-ja.mdx, src/content/docs/sdk/react-native/features/deep-links-ko.mdx, src/content/docs/sdk/react-native/features/deep-links-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:sxvu4f5hhn1o
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/4042ef78f60cfe5fefff969ea05200129a2336c6
=> Smartling translations are updated for commit 4042ef78f60cfe5fefff969ea05200129a2336c6 from main

src/content/docs/sdk/android/features/short-links-ja.mdx, src/content/docs/sdk/android/features/short-links-ko.mdx, src/content/docs/sdk/android/features/short-links-zh.mdx, src/content/docs/sdk/cocos2dx/features/short-links-ja.mdx, src/content/docs/sdk/cocos2dx/features/short-links-ko.mdx, src/content/docs/sdk/cocos2dx/features/short-links-zh.mdx, src/content/docs/sdk/cordova/features/short-links-ja.mdx, src/content/docs/sdk/cordova/features/short-links-ko.mdx, src/content/docs/sdk/cordova/features/short-links-zh.mdx, src/content/docs/sdk/flutter/features/short-links-ja.mdx, src/content/docs/sdk/flutter/features/short-links-ko.mdx, src/content/docs/sdk/flutter/features/short-links-zh.mdx, src/content/docs/sdk/ios/features/short-links-ja.mdx, src/content/docs/sdk/ios/features/short-links-ko.mdx, src/content/docs/sdk/ios/features/short-links-zh.mdx, src/content/docs/sdk/react-native/features/short-links-ja.mdx, src/content/docs/sdk/react-native/features/short-links-ko.mdx, src/content/docs/sdk/react-native/features/short-links-zh.mdx, src/content/docs/sdk/unity/features/short-links-ja.mdx, src/content/docs/sdk/unity/features/short-links-ko.mdx, src/content/docs/sdk/unity/features/short-links-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:1gy2naonlnny
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/2353c076fa8da8eb58f1efb1ae8c978d5d592a1b
=> Smartling translations are completed for commit 2353c076fa8da8eb58f1efb1ae8c978d5d592a1b from main

src/content/docs/sdk/android/index-ja.mdx, src/content/docs/sdk/android/index-ko.mdx, src/content/docs/sdk/android/index-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:clp209t3kxhs
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/029577738529a254db1dd17e8f59be4eb1f487a0
=> Smartling translations are updated for commit 029577738529a254db1dd17e8f59be4eb1f487a0 from main

src/content/docs/api/rs-api/csv.mdx, src/content/docs/api/rs-api/events.mdx, src/content/docs/api/rs-api/filters-data.mdx, src/content/docs/api/rs-api/index.mdx, src/content/docs/api/rs-api/pivot.mdx, src/content/docs/api/rs-api/reports.mdx
Closes https://adjustcom.atlassian.net/browse/ES-7425
=> Add filters_data information for collecting metrics in RS API

src/content/docs/sdk/android/features/deep-linking-ja.mdx, src/content/docs/sdk/android/features/deep-linking-ko.mdx, src/content/docs/sdk/android/features/deep-linking-zh.mdx, src/content/docs/sdk/android/features/short-links-ja.mdx, src/content/docs/sdk/android/features/short-links-ko.mdx, src/content/docs/sdk/android/features/short-links-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:o0f2i1frc1r7
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/66cae0ffc045e7bc78a0d620533f1cfeb143ab86
=> Smartling translations are completed for commit 66cae0ffc045e7bc78a0d620533f1cfeb143ab86 from main

src/content/docs/sdk/flutter/features/skad.mdx, src/content/docs/sdk/react-native/features/skad.mdx, src/content/docs/sdk/unity/features/skad.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18044
=> Add SKAN 4.0 docs for cross-platform SDKs

src/content/docs/sdk/android/integrations/signature-library.mdx, src/content/docs/sdk/ios/integrations/signature-library.mdx, src/content/docs/sdk/unity/integrations/signature-library.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18257
=> Add information about external obfuscation tools

src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:liwyyatd5hjf
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/a7f7f9cc1476eae6aeab23eb34683c62aab3ce25
=> Smartling translations are updated for commit a7f7f9cc1476eae6aeab23eb34683c62aab3ce25 from main

src/content/docs/sdk/android/migration/v5-purchase-verification.mdx, src/content/docs/sdk/ios/migration/v5-purchase-verification.mdx, src/content/docs/sdk/unity/migration/v5-purchase-verification.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18340
=> Add transition guides for Purchase Verification

src/content/docs/sdk/android/migration/v5-purchase-verification.mdx, src/content/docs/sdk/android/migration/web-v4-to-v5.mdx, src/content/docs/sdk/ios/index.mdx, src/content/docs/sdk/ios/migration/v5-purchase-verification.mdx, src/content/docs/sdk/ios/migration/web-v4-to-v5.mdx, src/content/docs/sdk/ios/plugins/facebook-pixel.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18258
=> Add web bridge migration guides for iOS and Android v5

src/content/docs/sdk/android/features/privacy.mdx, src/content/docs/sdk/cocos2dx/features/privacy.mdx, src/content/docs/sdk/cordova/features/privacy.mdx, src/content/docs/sdk/flutter/features/privacy.mdx, src/content/docs/sdk/ios/features/privacy.mdx, src/content/docs/sdk/react-native/features/privacy.mdx, src/content/docs/sdk/unity/features/privacy.mdx
Closes https://adjustcom.atlassian.net/browse/ES-7671
=> Update Unity COPPA compliance docs

src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:tgepfoqnh2fc
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/debc687ad0c5017a4a5d6320892889112a9463c6
=> Smartling translations are updated for commit debc687ad0c5017a4a5d6320892889112a9463c6 from main

src/content/docs/sdk/unity/migration/v4-to-v5.mdx
Closes https://adjustcom.atlassian.net/browse/ES-7721
=> Update setAttConsentWaitingInterval description

src/content/docs/sdk/android/features/privacy-ja.mdx, src/content/docs/sdk/android/features/privacy-ko.mdx, src/content/docs/sdk/android/features/privacy-zh.mdx, src/content/docs/sdk/cocos2dx/features/privacy-ja.mdx, src/content/docs/sdk/cocos2dx/features/privacy-ko.mdx, src/content/docs/sdk/cocos2dx/features/privacy-zh.mdx, src/content/docs/sdk/cordova/features/privacy-ja.mdx, src/content/docs/sdk/cordova/features/privacy-ko.mdx, src/content/docs/sdk/cordova/features/privacy-zh.mdx, src/content/docs/sdk/flutter/features/privacy-ja.mdx, src/content/docs/sdk/flutter/features/privacy-ko.mdx, src/content/docs/sdk/flutter/features/privacy-zh.mdx, src/content/docs/sdk/ios/features/privacy-ja.mdx, src/content/docs/sdk/ios/features/privacy-ko.mdx, src/content/docs/sdk/ios/features/privacy-zh.mdx, src/content/docs/sdk/react-native/features/privacy-ja.mdx, src/content/docs/sdk/react-native/features/privacy-ko.mdx, src/content/docs/sdk/react-native/features/privacy-zh.mdx, src/content/docs/sdk/unity/features/privacy-ja.mdx, src/content/docs/sdk/unity/features/privacy-ko.mdx, src/content/docs/sdk/unity/features/privacy-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:xpzorrdldn84
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/fed86129f07e43b2b4e73309793c4b3a99d2573f
=> Smartling translations are completed for commit fed86129f07e43b2b4e73309793c4b3a99d2573f from main

src/content/docs/sdk/android/migration/v5-purchase-verification-ja.mdx, src/content/docs/sdk/android/migration/v5-purchase-verification-ko.mdx, src/content/docs/sdk/android/migration/v5-purchase-verification-zh.mdx, src/content/docs/sdk/ios/migration/v5-purchase-verification-ja.mdx, src/content/docs/sdk/ios/migration/v5-purchase-verification-ko.mdx, src/content/docs/sdk/ios/migration/v5-purchase-verification-zh.mdx, src/content/docs/sdk/unity/migration/v5-purchase-verification-ja.mdx, src/content/docs/sdk/unity/migration/v5-purchase-verification-ko.mdx, src/content/docs/sdk/unity/migration/v5-purchase-verification-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:v45ojebkesmf
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/a37d7850342ead6ba5b393deadd3eb6a1687152a
=> Smartling translations are completed for commit a37d7850342ead6ba5b393deadd3eb6a1687152a from main

src/content/docs/sdk/android/integrations/signature-library-ja.mdx, src/content/docs/sdk/android/integrations/signature-library-ko.mdx, src/content/docs/sdk/android/integrations/signature-library-zh.mdx, src/content/docs/sdk/ios/integrations/signature-library-ja.mdx, src/content/docs/sdk/ios/integrations/signature-library-ko.mdx, src/content/docs/sdk/ios/integrations/signature-library-zh.mdx, src/content/docs/sdk/unity/integrations/signature-library-ja.mdx, src/content/docs/sdk/unity/integrations/signature-library-ko.mdx, src/content/docs/sdk/unity/integrations/signature-library-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:m2mjxtzlxmtl
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/2f17847b65639811619f07c93f2973d9c0b4e9b8
=> Smartling translations are completed for commit 2f17847b65639811619f07c93f2973d9c0b4e9b8 from main

src/content/docs/api/s2s-api/events-ja.mdx, src/content/docs/api/s2s-api/events-ko.mdx, src/content/docs/api/s2s-api/events-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:4trjduastguv
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/f3854115784491763cf7db122f69490f96dac252
=> Smartling translations are completed for commit f3854115784491763cf7db122f69490f96dac252 from main

src/content/docs/sdk/android/features/callbacks-ja.mdx, src/content/docs/sdk/android/features/callbacks-ko.mdx, src/content/docs/sdk/android/features/callbacks-zh.mdx, src/content/docs/sdk/android/features/deep-linking-ja.mdx, src/content/docs/sdk/android/features/deep-linking-ko.mdx, src/content/docs/sdk/android/features/deep-linking-zh.mdx, src/content/docs/sdk/android/features/device-info-ja.mdx, src/content/docs/sdk/android/features/device-info-ko.mdx, src/content/docs/sdk/android/features/device-info-zh.mdx, src/content/docs/sdk/android/features/privacy-ja.mdx, src/content/docs/sdk/android/features/privacy-ko.mdx, src/content/docs/sdk/android/features/privacy-zh.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:cwrqwymqxxqu
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/baa864f785b86c057e8340e1b16cbc90d227d5c7
=> Smartling translations are completed for commit baa864f785b86c057e8340e1b16cbc90d227d5c7 from main

src/content/docs/sdk/unity/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/unity/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/unity/migration/v4-to-v5-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:kfnp7hdio6qv
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/4c2f72934302dd4bb6228196aa53681206d1da67
=> Smartling translations are completed for commit 4c2f72934302dd4bb6228196aa53681206d1da67 from main

src/content/docs/sdk/android/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/android/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/android/migration/v4-to-v5-zh.mdx, src/content/docs/sdk/android/setup/preinstalled-ja.mdx, src/content/docs/sdk/android/setup/preinstalled-ko.mdx, src/content/docs/sdk/android/setup/preinstalled-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:7mpebmjsl0a1
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/c1188bd9c9777b825ee42cbffb4d6c7b1d179f0b
=> Smartling translations are completed for commit c1188bd9c9777b825ee42cbffb4d6c7b1d179f0b from main

src/content/docs/api/blocklist-api/blocklist-ja.mdx, src/content/docs/api/blocklist-api/blocklist-ko.mdx, src/content/docs/api/blocklist-api/blocklist-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:tcibf2y6qo6e
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/1eca6d96d08da394302703bb4d375908ff398dd3
=> Smartling translations are completed for commit 1eca6d96d08da394302703bb4d375908ff398dd3 from main

src/content/docs/api/blocklist-api/blocklist-ja.mdx, src/content/docs/api/blocklist-api/blocklist-ko.mdx, src/content/docs/api/blocklist-api/blocklist-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:tecwzoogzyx3
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/9061e189ae667da858f52c18da60e9a8aced3c91
=> Smartling translations are completed for commit 9061e189ae667da858f52c18da60e9a8aced3c91 from main

src/content/docs/sdk/ios/configuration-ja.mdx, src/content/docs/sdk/ios/configuration-ko.mdx, src/content/docs/sdk/ios/configuration-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:agtvitdj7rbb
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/904bc9225846703acd89029bcfff652c4247016c
=> Smartling translations are updated for commit 904bc9225846703acd89029bcfff652c4247016c from main

package.json, src/content/docs/sdk/flutter/features/ad-revenue.mdx, src/content/docs/sdk/flutter/features/short-links.mdx, src/content/docs/sdk/flutter/features/subscriptions.mdx, src/content/docs/sdk/flutter/integrations/tradplus.mdx, src/content/docs/sdk/flutter/migration/index.mdx, src/content/docs/sdk/flutter/migration/v4-to-v5.mdx, src/content/docs/sdk/ios/configuration-ja.mdx, src/content/docs/sdk/ios/configuration-ko.mdx, src/content/docs/sdk/ios/configuration-zh.mdx, src/content/docs/sdk/ios/configuration.mdx
SDK v5 migration guide for Flutter
=> Adapp 18520 create flutter sdk v4 to v5 migration and v5 integration guide

src/content/docs/sdk/flutter/features/events-ja.mdx, src/content/docs/sdk/flutter/features/events-ko.mdx, src/content/docs/sdk/flutter/features/events-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:ous7kq2ak5q2
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/1902cd222008a98869ae5d044469b518e3c35f55
=> Smartling translations are completed for commit 1902cd222008a98869ae5d044469b518e3c35f55 from main

src/content/docs/api/ad-spend-api-ja.mdx, src/content/docs/api/ad-spend-api-ko.mdx, src/content/docs/api/ad-spend-api-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:9unrjxmptvtb
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/c70d626c4d2704650aac09ddcdc8141f80d651b5
=> Smartling translations are completed for commit c70d626c4d2704650aac09ddcdc8141f80d651b5 from main

src/content/docs/api/device-api-ja.mdx, src/content/docs/api/device-api-ko.mdx, src/content/docs/api/device-api-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:o0ie6ruxfxs6
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/ace935f83d9dafe140078c7eb0ddc1f747e2f8f6
=> Smartling translations are completed for commit ace935f83d9dafe140078c7eb0ddc1f747e2f8f6 from main

src/content/docs/api/blocklist-ja.mdx, src/content/docs/api/blocklist-ko.mdx, src/content/docs/api/blocklist-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:v5ncru98uy9u
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/084c92d6ce1f250e82e9b5ada35ca6120c4b1e71
=> Smartling translations are completed for commit 084c92d6ce1f250e82e9b5ada35ca6120c4b1e71 from main

src/content/docs/sdk/unity/index-ja.mdx, src/content/docs/sdk/unity/index-ko.mdx, src/content/docs/sdk/unity/index-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:nf0w8mzhdlvq
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/223ca52df73a4f09346672c4f53de56a6f51abdb
=> Smartling translations are completed for commit 223ca52df73a4f09346672c4f53de56a6f51abdb from main

src/content/docs/sdk/flutter/features/ad-revenue-ja.mdx, src/content/docs/sdk/flutter/features/ad-revenue-ko.mdx, src/content/docs/sdk/flutter/features/ad-revenue-zh.mdx, src/content/docs/sdk/flutter/features/short-links-ja.mdx, src/content/docs/sdk/flutter/features/short-links-ko.mdx, src/content/docs/sdk/flutter/features/short-links-zh.mdx, src/content/docs/sdk/flutter/features/subscriptions-ja.mdx, src/content/docs/sdk/flutter/features/subscriptions-ko.mdx, src/content/docs/sdk/flutter/features/subscriptions-zh.mdx, src/content/docs/sdk/flutter/integrations/tradplus-ja.mdx, src/content/docs/sdk/flutter/integrations/tradplus-ko.mdx, src/content/docs/sdk/flutter/integrations/tradplus-zh.mdx, src/content/docs/sdk/flutter/migration/index-ja.mdx, src/content/docs/sdk/flutter/migration/index-ko.mdx, src/content/docs/sdk/flutter/migration/index-zh.mdx, src/content/docs/sdk/flutter/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/flutter/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/flutter/migration/v4-to-v5-zh.mdx
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:xgaherk3iv2o
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/08b586904a6c3dcb5a860901481a809b28ebe7ed
=> Smartling translations are completed for commit 08b586904a6c3dcb5a860901481a809b28ebe7ed from main

package.json, src/components/Layout/LeftSidebar/Sidebar.astro, src/components/Layout/LeftSidebar/SidebarHeader.astro, src/components/Layout/PageContent/PageContent.astro, src/components/TableOfContents.astro, src/components/Version/ApiVersionSwitch.tsx, src/components/Version/SdkVersionSwitch.tsx, src/content/config.ts, src/content/docs/sdk/android/v4/index.mdx, src/content/docs/sdk/android/v5/index.mdx, src/layouts/MainLayout.astro, src/store/apiVersionsStore.ts, src/store/sdkVersionsStore.ts, src/utils/helpers/navigation/getNavigationEntries.ts, src/utils/helpers/navigation/types.ts
https://adjustcom.atlassian.net/browse/THC-1040
=> THC 1040 create generic versioning

src/content/docs/sdk/flutter/plugins/index.mdx, src/content/docs/sdk/react-native/configuration.mdx, src/content/docs/sdk/react-native/features/ad-revenue.mdx, src/content/docs/sdk/react-native/features/att.mdx, src/content/docs/sdk/react-native/features/attribution.mdx, src/content/docs/sdk/react-native/features/callbacks.mdx, src/content/docs/sdk/react-native/features/deep-links.mdx, src/content/docs/sdk/react-native/features/events.mdx, src/content/docs/sdk/react-native/features/preinstalled.mdx, src/content/docs/sdk/react-native/features/privacy.mdx, src/content/docs/sdk/react-native/features/purchase-verification.mdx, src/content/docs/sdk/react-native/features/session-parameters.mdx, src/content/docs/sdk/react-native/features/short-links.mdx, src/content/docs/sdk/react-native/features/skad.mdx, src/content/docs/sdk/react-native/features/subscriptions.mdx, src/content/docs/sdk/react-native/index.mdx, src/content/docs/sdk/react-native/plugins/meta-install-referrer.mdx, src/integrations/fetchSdkVersions.ts
Updated all features for React Native SDK v5
=> Rn v5 integrations

src/content/docs/sdk/ios/features/deep-links/direct-ja.mdx, src/content/docs/sdk/ios/features/deep-links/direct-ko.mdx, src/content/docs/sdk/ios/features/deep-links/direct-zh.mdx, src/content/docs/sdk/ios/migration/v4-to-v5-ja.mdx, src/content/docs/sdk/ios/migration/v4-to-v5-ko.mdx, src/content/docs/sdk/ios/migration/v4-to-v5-zh.mdx
Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:aycyviygttpp
Here is a link to the source commit which triggered this update - https://github.com/adjust/dev-docs/commit/d46d5d8ad9749ed3afd359bf2e99ff3e5463db1f
=> Smartling translations are updated for commit d46d5d8ad9749ed3afd359bf2e99ff3e5463db1f from main

src/content/docs/sdk/cocos2dx/features/subscriptions.mdx, src/content/docs/sdk/cordova/features/subscriptions.mdx, src/content/docs/sdk/flutter/features/subscriptions.mdx, src/content/docs/sdk/ios/features/subscriptions.mdx, src/content/docs/sdk/react-native/features/subscriptions.mdx, src/content/docs/sdk/unity/features/subscriptions.mdx
This PR is updating App Store subscription sales region docs to link to StoreKit2 API.
=> App Store subscription sales region update

src/components/pages/search/Pagination.tsx
=> Fixed margin for the hits when we don`t have pagination

markdoc.config.mjs, src/components/DefList.astro, src/components/utils/parseDefList.ts
Adds support for the new `{% deflist %}` tag.
=> Add support for definition lists

.github/scripts/fix_i18n.py, .prettierrc, package.json, src/content/docs/zh/sdk/cocos2dx/v5/configuration.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/ad-revenue.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/att.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/attribution.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/callbacks.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/deep-links.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/device-info.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/events.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/global-parameters.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/index.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/preinstalled.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/privacy.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/purchase-verification.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/short-links.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/skan.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/features/subscriptions.mdoc, src/content/docs/zh/sdk/cocos2dx/v5/index.mdoc, src/content/docs/zh/sdk/migration/cocos2dx/index.mdoc, src/content/docs/zh/sdk/migration/cocos2dx/v4-to-v5.mdoc
Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/aaa8fc6f/account-jobs/224fc9b33:bk2ut4uvi3za
Here is a link to the source commit which triggered translation - https://github.com/adjust/dev-docs/commit/5e5c452d7adcf6f5547363b03b51617e7d4e4e7a
=> Smartling translations are completed for commit 5e5c452d7adcf6f5547363b03b51617e7d4e4e7a from main

src/content/docs/en/sdk/flutter/v5/index.mdoc
Closes https://adjustcom.atlassian.net/browse/ADAPP-18841
=> Fix version macro

src/content/docs/en/sdk/android/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/android/v5/features/ad-revenue.mdx, src/content/docs/en/sdk/cocos2dx/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/cocos2dx/v5/features/ad-revenue.mdoc, src/content/docs/en/sdk/cordova/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/cordova/v5/features/ad-revenue.mdx, src/content/docs/en/sdk/flutter/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/flutter/v5/features/ad-revenue.mdx, src/content/docs/en/sdk/ios/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/ios/v5/features/ad-revenue.mdx, src/content/docs/en/sdk/react-native/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/react-native/v5/features/ad-revenue.mdx, src/content/docs/en/sdk/unity/v4/features/ad-revenue.mdx, src/content/docs/en/sdk/unity/v5/features/ad-revenue.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18844
=> Remove partner parameters callout from ad revenue docs

src/components/pages/search/HelpCenterHits/HelpCenterIndex.tsx, src/components/pages/search/HelpCenterHits/HelpCenterResultCard.tsx, src/components/pages/search/utils.ts, src/i18n/locales.ts
https://adjustcom.atlassian.net/browse/THC-1059
The same update for the Dev hub collection will be handled in the scope of another ticket, this PR includes updates only for the HC hits
=> THC-1059 updates for the tokenized fields on the Typesense

src/components/Layout/LeftSidebar/Sidebar.astro
Addresses an issue where on smaller screens, the currently selected sidebar item can appear offscreen
=> Scroll the currently selected sidebar item into view

src/content/docs/en/sdk/ios/v5/index.mdoc, src/content/docs/en/sdk/migration/ios/v4-to-v5.mdx
- Jira issue link: https://adjustcom.atlassian.net/browse/ADAPP-18859
Updates the iOS integration guide/migration guide to remove GitHub links from pod files. Adds missing version macro to ensure versions are kept up-to-date.
=> Update podfile information

src/content/docs/en/sdk/android/v4/integrations/signature-library.mdx, src/content/docs/en/sdk/android/v5/integrations/signature-library.mdx, src/content/docs/en/sdk/unity/v4/integrations/signature-library.mdx, src/content/docs/en/sdk/unity/v5/integrations/signature-library.mdx
Closes https://adjustcom.atlassian.net/browse/ADAPP-18845
=> [signature-library] [android] Reflect Signature 16KB page size aligned libraries

src/content/docs/en/sdk/ios/v4/integrations/signature-library.mdx, src/content/docs/en/sdk/ios/v5/integrations/signature-library.mdx, src/content/docs/en/sdk/unity/v4/integrations/signature-library.mdx, src/content/docs/en/sdk/unity/v5/integrations/signature-library.mdx
- Jira issue link: https://adjustcom.atlassian.net/browse/ADAPP-18892
| Cordova                 | :white_check_mark: | :white_check_mark: | …
=> [signature] [ios] Clarify `Upload symbols failed` warning

src/components/pages/search/DevHubHits/DevHubIndex.tsx, src/components/pages/search/DevHubHits/DevHubSearchResultCard.tsx
https://adjustcom.atlassian.net/browse/THC-1068
=> THC 1068 optimize dev hub search function

src/content/docs/en/sdk/android/v4/features/subscriptions.mdx, src/content/docs/en/sdk/android/v5/features/subscriptions.mdx, src/content/docs/en/sdk/cocos2dx/v4/features/subscriptions.mdx, src/content/docs/en/sdk/cocos2dx/v5/features/subscriptions.mdoc, src/content/docs/en/sdk/cordova/v4/features/subscriptions.mdx, src/content/docs/en/sdk/cordova/v5/features/subscriptions.mdx, src/content/docs/en/sdk/flutter/v4/features/subscriptions.mdx, src/content/docs/en/sdk/flutter/v5/features/subscriptions.mdx, src/content/docs/en/sdk/ios/v4/features/subscriptions.mdx, src/content/docs/en/sdk/ios/v5/features/subscriptions.mdx, src/content/docs/en/sdk/react-native/v4/features/subscriptions.mdx, src/content/docs/en/sdk/react-native/v5/features/subscriptions.mdx, src/content/docs/en/sdk/testing/subscription-recording.mdx, src/content/docs/en/sdk/unity/v4/features/subscriptions.mdx, src/content/docs/en/sdk/unity/v5/features/subscriptions.mdx
=> Updates for Subscription v3

ec.config.mjs, src/content/docs/en/sdk/flutter/v5/features/deep-links.mdx
=> changed property declaration codeblock

src/content/docs/en/sdk/ios/v5/features/att.mdx, src/content/docs/en/sdk/react-native/v5/features/att.mdx
=> changed attconsentwaitinginterval to 360

src/content/docs/en/api/ad-spend-api.mdx
=> Added cost_amount

src/content/docs/en/sdk/web/index.mdx
- Jira issue link: https://adjustcom.atlassian.net/browse/FECORE-17
Removed the restriction warning
Before
After:
=> [FECORE-17]: Removed the warning restriction

src/content/docs/ja/sdk/android/v5/features/deep-linking.mdx, src/content/docs/ko/sdk/android/v5/features/deep-linking.mdx, src/content/docs/zh/sdk/android/v5/features/deep-linking.mdx
- Jira issue link: https://adjustcom.atlassian.net/browse/FECORE-627
For some reason when this doc was translated or updated(~5 months ago), the code tag for this block was removed from the localized version, looks like a Smartling issue. I`ve added a code tag for this block and it fixed a problem
=> [FECORE-627] fixed v5 android features localized docs

src/pages/[lang]/index.astro
- Jira issue link: https://adjustcom.atlassian.net/browse/FECORE-620
Updated padding for main page
##Screenshots
Before:
After:
=> [FECORE-620]: Updated padding for main page

.github/CODEOWNERS
- Jira issue link: https://adjustcom.atlassian.net/browse/FECORE-673
Added CODEOWNERS GitHub file
=> [FECORE-673]: added codeowners file

src/content/docs/en/sdk/web/index.mdx
- Jira: https://adjustcom.atlassian.net/browse/DSM-3688
Updates Web SDK installation section to refer the most recent version of the SDK.
Updates Subresource Integrity section to contain most recent SDK version with valid integrity hash and adds clarification note on it.
| Web                     | :white_check_mark: | :white_check_mark: | :white_check_mark: |
=> Update Web SDK SRI section

src/content/docs/en/sdk/android/v5/features/deep-linking.mdx, src/content/docs/en/sdk/android/v5/features/short-links.mdx, src/content/docs/en/sdk/ios/v5/features/deep-links/direct.mdx, src/content/docs/en/sdk/ios/v5/features/short-links.mdx
- Jira issue link: https://adjustcom.atlassian.net/browse/SDK-2213
Improve the `ADJDeeplink` class to allow customers also to send organic search referrer. 
| Platform                | ZH                 | JA                 | KO                 | EN
| ----------------------- | ------------------ | ------------------ | ------------------ | -----------------|
| iOS                     | :x: | :x: | :x: |✅ 
| Android                 | :x: | :x: | :x: |✅
=> Add handling deeplinks with referrer

src/content/docs/en/api/campaign-api.mdx
Updates Campaign Api documentation to reflect latest api version for EN locale
| Cordova                 | …
=> Update docs for Campaign Api

src/content/docs/en/sdk/ios/v5/features/att.mdx
Changes in code snippets format and content
| Platform                | ZH                 | JA                 | KO                 | EN
| ----------------------- | ------------------ | ------------------ | ------------------ | -----------------|
| iOS                     | :x: | :x: | :x: |✅
=> AppTrackingTransparency disabled - code snippets improvements

src/content/docs/en/sdk/android/v5/plugins/samsung-clouddev.mdx
=> Update version for Samsung Clouddev Plugin
